FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "setuptools==67.8.0" mlflow[postgres]==2.12.1 psycopg2-binary

EXPOSE 5000

ENTRYPOINT ["mlflow", "server"]